#!/bin/bash
# Sky1 Linux bootloader installation script
# Installs patched GRUB and generates initial grub.cfg
# Runs outside chroot (dontChroot: true) - receives ROOT as $1 from Calamares
#
# Subsequent kernel updates are handled by /usr/share/sky1/update-boot
# via postinst hooks, which will regenerate grub.cfg automatically.

set -e

exec >> /tmp/bootloader.log 2>&1
echo "=== Sky1 Bootloader Installation ==="
echo "Date: $(date)"
echo "ROOT_MOUNT_POINT=$ROOT_MOUNT_POINT"

# Use Calamares-provided ROOT (passed as $1, fallback to env var)
CHROOT="${1:-$ROOT_MOUNT_POINT}"

if [ -z "$CHROOT" ] || [ ! -d "$CHROOT" ]; then
    echo "ERROR: ROOT_MOUNT_POINT not set or invalid"
    echo "Environment:"
    env | sort
    echo "Mount output:"
    mount
    exit 1
fi

echo "Chroot path: $CHROOT"

# Find EFI mount point
EFI_MOUNT=$(mount | grep "$CHROOT/boot/efi" | awk '{print $3}')
if [ -z "$EFI_MOUNT" ]; then
    # Try to find EFI partition and mount it
    EFI_DEV=$(grep "/boot/efi" "$CHROOT/etc/fstab" | awk '{print $1}')
    if [ -n "$EFI_DEV" ]; then
        echo "Mounting EFI partition $EFI_DEV"
        mkdir -p "$CHROOT/boot/efi"
        mount "$EFI_DEV" "$CHROOT/boot/efi"
        EFI_MOUNT="$CHROOT/boot/efi"
    else
        echo "ERROR: Could not find EFI partition"
        cat "$CHROOT/etc/fstab"
        exit 1
    fi
fi

echo "EFI mount: $EFI_MOUNT"

PATCHED_GRUB="$CHROOT/usr/share/sky1/grubaa64-install.efi"

# Get root partition UUID from fstab
ROOT_UUID=$(grep -E '^\s*UUID=[^ ]+\s+/\s' "$CHROOT/etc/fstab" | grep -oP 'UUID=\K[^ ]+' | head -1)

if [ -z "$ROOT_UUID" ]; then
    echo "ERROR: Could not determine root partition UUID"
    cat "$CHROOT/etc/fstab"
    exit 1
fi

echo "Root UUID: $ROOT_UUID"

# Create EFI directory structure
mkdir -p "$EFI_MOUNT/EFI/BOOT"
mkdir -p "$EFI_MOUNT/EFI/sky1"
mkdir -p "$EFI_MOUNT/GRUB"

# Copy patched GRUB (with CTRL key fix)
cp "$PATCHED_GRUB" "$EFI_MOUNT/EFI/BOOT/BOOTAA64.EFI"
cp "$PATCHED_GRUB" "$EFI_MOUNT/EFI/sky1/grubaa64.efi"

echo "Copied patched GRUB"

# Detect board from host device tree (we're running on the target hardware)
BOARD_DTB="sky1-orion-o6.dtb"
if [ -f /sys/firmware/devicetree/base/compatible ]; then
    COMPAT=$(tr '\0' '\n' < /sys/firmware/devicetree/base/compatible | head -1)
    case "$COMPAT" in
        radxa,orion-o6n*) BOARD_DTB="sky1-orion-o6n.dtb" ;;
        radxa,orion-o6*)  BOARD_DTB="sky1-orion-o6.dtb" ;;
        *)                echo "Warning: Unknown board '$COMPAT', using O6 DTB" ;;
    esac
fi

echo "Board DTB: $BOARD_DTB"

# Find kernel version
KERNEL_VERSION=$(ls "$CHROOT/boot/vmlinuz-"* 2>/dev/null | head -1 | sed "s|$CHROOT/boot/vmlinuz-||")
if [ -z "$KERNEL_VERSION" ]; then
    echo "ERROR: Could not find kernel"
    ls -la "$CHROOT/boot/"
    exit 1
fi

echo "Kernel version: $KERNEL_VERSION"

# Ensure DTBs are in /boot/dtbs
mkdir -p "$CHROOT/boot/dtbs"
DTB_SOURCE="$CHROOT/usr/lib/linux-image-$KERNEL_VERSION/cix"
if [ -d "$DTB_SOURCE" ]; then
    cp "$DTB_SOURCE"/sky1-*.dtb "$CHROOT/boot/dtbs/" 2>/dev/null || true
fi

# Common kernel command line (verbose, no quiet/splash)
CMDLINE="loglevel=7 console=tty0 console=ttyAMA2,115200"
CMDLINE+=" efi=noruntime earlycon=efifb earlycon=pl011,0x040d0000 acpi=off"
CMDLINE+=" clk_ignore_unused linlon_dp.enable_fb=1 linlon_dp.enable_render=0"
CMDLINE+=" fbcon=map:01111111 keep_bootcon panic=30"
CMDLINE+=" root=UUID=$ROOT_UUID rootwait rw"

# Generate grub.cfg
cat > "$EFI_MOUNT/GRUB/grub.cfg" << EOF
# Sky1 Linux GRUB Configuration
# Auto-generated by install-bootloader.sh
# Subsequent updates managed by /usr/share/sky1/update-boot

set term=vt100
set default=0
set timeout=5

insmod part_gpt
insmod fat
insmod ext2

search.fs_uuid $ROOT_UUID root
set prefix=(\$root)/boot/grub

menuentry 'Sky1 Linux ${KERNEL_VERSION}' {
    devicetree (\$root)/boot/dtbs/${BOARD_DTB}
    linux (\$root)/boot/vmlinuz-${KERNEL_VERSION} \\
        ${CMDLINE}
    initrd (\$root)/boot/initrd.img-${KERNEL_VERSION}
}

menuentry 'Sky1 Linux ${KERNEL_VERSION} (recovery)' {
    devicetree (\$root)/boot/dtbs/${BOARD_DTB}
    linux (\$root)/boot/vmlinuz-${KERNEL_VERSION} \\
        ${CMDLINE} single
    initrd (\$root)/boot/initrd.img-${KERNEL_VERSION}
}
EOF

echo "Generated grub.cfg"
cat "$EFI_MOUNT/GRUB/grub.cfg"

echo "=== EFI Contents ==="
ls -laR "$EFI_MOUNT"

echo "=== Bootloader installation complete ==="
