#!/bin/bash
# Sky1 Linux bootloader installation script
# Installs patched GRUB with CTRL key fix and generates proper grub.cfg
# Runs outside chroot (dontChroot: true) - Calamares passes ROOT_MOUNT_POINT

set -e

exec >> /tmp/bootloader.log 2>&1
echo "=== Sky1 Bootloader Installation ==="
echo "Date: $(date)"
echo "ROOT_MOUNT_POINT=$ROOT_MOUNT_POINT"

# Use Calamares-provided ROOT_MOUNT_POINT
CHROOT="$ROOT_MOUNT_POINT"

if [ -z "$CHROOT" ] || [ ! -d "$CHROOT" ]; then
    echo "ERROR: ROOT_MOUNT_POINT not set or invalid"
    echo "Environment:"
    env | sort
    echo "Mount output:"
    mount
    exit 1
fi

echo "Chroot path: $CHROOT"

# Find EFI mount point
EFI_MOUNT=$(mount | grep "$CHROOT/boot/efi" | awk '{print $3}')
if [ -z "$EFI_MOUNT" ]; then
    # Try to find EFI partition and mount it
    EFI_DEV=$(grep "/boot/efi" "$CHROOT/etc/fstab" | awk '{print $1}')
    if [ -n "$EFI_DEV" ]; then
        echo "Mounting EFI partition $EFI_DEV"
        mkdir -p "$CHROOT/boot/efi"
        mount "$EFI_DEV" "$CHROOT/boot/efi"
        EFI_MOUNT="$CHROOT/boot/efi"
    else
        echo "ERROR: Could not find EFI partition"
        cat "$CHROOT/etc/fstab"
        exit 1
    fi
fi

echo "EFI mount: $EFI_MOUNT"

PATCHED_GRUB="$CHROOT/usr/share/sky1/grubaa64-sky1.efi"

# Get root partition UUID from fstab
ROOT_UUID=$(grep -E '^\s*UUID=[^ ]+\s+/\s' "$CHROOT/etc/fstab" | grep -oP 'UUID=\K[^ ]+' | head -1)

if [ -z "$ROOT_UUID" ]; then
    echo "ERROR: Could not determine root partition UUID"
    cat "$CHROOT/etc/fstab"
    exit 1
fi

echo "Root UUID: $ROOT_UUID"

# Create EFI directory structure
mkdir -p "$EFI_MOUNT/EFI/BOOT"
mkdir -p "$EFI_MOUNT/EFI/sky1"
mkdir -p "$EFI_MOUNT/GRUB"

# Copy patched GRUB (with CTRL key fix)
cp "$PATCHED_GRUB" "$EFI_MOUNT/EFI/BOOT/BOOTAA64.EFI"
cp "$PATCHED_GRUB" "$EFI_MOUNT/EFI/sky1/grubaa64.efi"

echo "Copied patched GRUB"

# Find kernel version
KERNEL_VERSION=$(ls "$CHROOT/boot/vmlinuz-"* 2>/dev/null | head -1 | sed "s|$CHROOT/boot/vmlinuz-||")
if [ -z "$KERNEL_VERSION" ]; then
    echo "ERROR: Could not find kernel"
    ls -la "$CHROOT/boot/"
    exit 1
fi

echo "Kernel version: $KERNEL_VERSION"

# Generate grub.cfg
cat > "$EFI_MOUNT/GRUB/GRUB.CFG" << EOF
# Sky1 Linux GRUB Configuration
# Auto-generated by install-bootloader.sh

set term=vt100
set default=0
set timeout=5

search.fs_uuid $ROOT_UUID root
set prefix=(\$root)/boot/grub

menuentry 'Sky1 Linux' {
    devicetree (\$root)/boot/dtbs/sky1-orion-o6.dtb
    linux (\$root)/boot/vmlinuz-$KERNEL_VERSION \\
        console=tty0 \\
        efi=noruntime \\
        acpi=off \\
        clk_ignore_unused \\
        linlon_dp.enable_fb=1 \\
        linlon_dp.enable_render=0 \\
        fbcon=map:01111111 \\
        panic=30 \\
        quiet splash \\
        root=UUID=$ROOT_UUID rootwait rw
    initrd (\$root)/boot/initrd.img-$KERNEL_VERSION
}

menuentry 'Sky1 Linux (verbose)' {
    devicetree (\$root)/boot/dtbs/sky1-orion-o6.dtb
    linux (\$root)/boot/vmlinuz-$KERNEL_VERSION \\
        loglevel=7 \\
        console=tty0 \\
        console=ttyAMA2,115200 \\
        efi=noruntime \\
        earlycon=pl011,0x040d0000 \\
        acpi=off \\
        clk_ignore_unused \\
        linlon_dp.enable_fb=1 \\
        linlon_dp.enable_render=0 \\
        fbcon=map:01111111 \\
        panic=30 \\
        root=UUID=$ROOT_UUID rootwait rw
    initrd (\$root)/boot/initrd.img-$KERNEL_VERSION
}

menuentry 'Sky1 Linux (recovery mode)' {
    devicetree (\$root)/boot/dtbs/sky1-orion-o6.dtb
    linux (\$root)/boot/vmlinuz-$KERNEL_VERSION \\
        loglevel=7 \\
        console=tty0 \\
        console=ttyAMA2,115200 \\
        efi=noruntime \\
        earlycon=pl011,0x040d0000 \\
        acpi=off \\
        clk_ignore_unused \\
        linlon_dp.enable_fb=1 \\
        linlon_dp.enable_render=0 \\
        fbcon=map:01111111 \\
        panic=30 \\
        single \\
        root=UUID=$ROOT_UUID rootwait rw
    initrd (\$root)/boot/initrd.img-$KERNEL_VERSION
}
EOF

echo "Generated GRUB.CFG"
cat "$EFI_MOUNT/GRUB/GRUB.CFG"

echo "=== EFI Contents ==="
ls -laR "$EFI_MOUNT"

echo "=== Bootloader installation complete ==="
